name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (GitHub Packages)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@codeiqlabs'

      - name: Install
        run: npm ci

      # Will either:
      #  - open/refresh a "Version Packages" PR when there are pending changesets, or
      #  - publish after that PR is merged (creating a Git tag + GitHub Release).
      - name: Create release PR or publish
        uses: changesets/action@v1
        with:
          publish: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional debugging
      - name: Who am I?
        if: always()
        run: |
          npm config get registry
          npm whoami || true
